services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_db_prod:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  server_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:  
  postgres_db_prod: