services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  server:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:  
  postgres_db: